# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CP_Server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x43P_Server.proto\"<\n\x13TransmitFileRequest\x12\x10\n\x08\x66ileName\x18\x01 \x01(\t\x12\x13\n\x0b\x66ileContent\x18\x02 \x01(\t\".\n\x14TransmitFileResponse\x12\x16\n\x0etransmitStatus\x18\x01 \x01(\t\"\"\n\x0eGetFileRequest\x12\x10\n\x08\x66ileName\x18\x01 \x01(\t\"8\n\x0fGetFileResponse\x12\x10\n\x08\x66ileName\x18\x01 \x01(\t\x12\x13\n\x0b\x66ileContent\x18\x02 \x01(\t\";\n\x13requestTokenRequest\x12\x11\n\tprocessID\x18\x01 \x01(\x05\x12\x11\n\tseqNumber\x18\x02 \x01(\x05\"_\n\x14requestTokenResponse\x12\x17\n\rrequestStatus\x18\x01 \x01(\tH\x00\x12\"\n\x05token\x18\x02 \x01(\x0b\x32\x11.sendTokenRequestH\x00\x42\n\n\x08response\")\n\x10sendTokenRequest\x12\t\n\x01Q\x18\x01 \x03(\x05\x12\n\n\x02LN\x18\x02 \x03(\x05\"*\n\x11sendTokenResponse\x12\x15\n\rrequestStatus\x18\x01 \x01(\t2\xfe\x01\n\x16\x43ontentProvider_Server\x12;\n\x0cTransmitFile\x12\x14.TransmitFileRequest\x1a\x15.TransmitFileResponse\x12,\n\x07GetFile\x12\x0f.GetFileRequest\x1a\x10.GetFileResponse\x12\x42\n\x13receiveTokenRequest\x12\x14.requestTokenRequest\x1a\x15.requestTokenResponse\x12\x35\n\x0creceiveToken\x12\x11.sendTokenRequest\x1a\x12.sendTokenResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CP_Server_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TRANSMITFILEREQUEST']._serialized_start=19
  _globals['_TRANSMITFILEREQUEST']._serialized_end=79
  _globals['_TRANSMITFILERESPONSE']._serialized_start=81
  _globals['_TRANSMITFILERESPONSE']._serialized_end=127
  _globals['_GETFILEREQUEST']._serialized_start=129
  _globals['_GETFILEREQUEST']._serialized_end=163
  _globals['_GETFILERESPONSE']._serialized_start=165
  _globals['_GETFILERESPONSE']._serialized_end=221
  _globals['_REQUESTTOKENREQUEST']._serialized_start=223
  _globals['_REQUESTTOKENREQUEST']._serialized_end=282
  _globals['_REQUESTTOKENRESPONSE']._serialized_start=284
  _globals['_REQUESTTOKENRESPONSE']._serialized_end=379
  _globals['_SENDTOKENREQUEST']._serialized_start=381
  _globals['_SENDTOKENREQUEST']._serialized_end=422
  _globals['_SENDTOKENRESPONSE']._serialized_start=424
  _globals['_SENDTOKENRESPONSE']._serialized_end=466
  _globals['_CONTENTPROVIDER_SERVER']._serialized_start=469
  _globals['_CONTENTPROVIDER_SERVER']._serialized_end=723
# @@protoc_insertion_point(module_scope)
